### ISSUE TITLE
Ajax call

### ISSUE THREAD

**Issue by Mcghee-Jake** [team-makeSmart/CST336#10]
Requirement: 
- Project uses at least one AJAX call

**Comment by mdoussias** [comment]
Not sure yet what AJAX is, but if I work on the DB, my stuff will be done earlier.  So I think I can tackle this later, after I complete the DB.

**Comment by p12345vls** [comment]
I can help with this if necessary.

**Comment by mdoussias** [comment]
Hi Pavlos, If you want to help with this one that may be good.  
Since I don't yet know what AJAX is, I might not should have committed just yet.

**Comment by p12345vls** [comment]
One Ajax call is included in admin.php

**Comment by mdoussias** [comment]
Awesome.  Great job Pavlos.

**Comment by mdoussias** [comment]
This action is completed in admin.php

**Comment by Mcghee-Jake** [comment]
I also have an Ajax call in the store. I didn't even intend to, but the way I set up my search forms I was required to use Ajax.
