### ISSUE TITLE
images

### ISSUE THREAD

**Issue by Mcghee-Jake** [team-makeSmart/CST336#12]
We will need images for each item that we are selling. To make the design part much much easier for me **each picture should have the exact same dimensions as each other**. Whoever takes this on, Ill give you the ideal size when I get further along in the design, but you can at least start gathering images in the meantime as soon as some are added to the database.

**Comment by p12345vls** [comment]
Images sizes can be adjusted in css -- example:  witdh:300px; height:200px;

**Comment by p12345vls** [comment]
I will search for images, how many do we need?

**Comment by Mcghee-Jake** [comment]
That will crop the image but it won't scale it, the result is that parts of the image may be cut off. Though now that I think of it, I think bootstrap may have the capability to scale images, I'll look into that later

**Comment by Mcghee-Jake** [comment]
The requirements say that one table needs at least 20 records. So there's going to be 20 min, make sure to coordinate with Maco to see which plants you need images for.

**Comment by p12345vls** [comment]
About the pictures: What kind of pictures we need? Funny, or real? I mean for example books:
![donttouch](https://user-images.githubusercontent.com/32381448/42728516-c653ff0e-8770-11e8-8a8a-a48daab29cdc.jpg)
plants: 
![pirancha](https://user-images.githubusercontent.com/32381448/42728519-dcc3bd6a-8770-11e8-9dde-a8f76a05b6e2.jpg)
tools:
![scissors](https://user-images.githubusercontent.com/32381448/42728525-f4251512-8770-11e8-8bbc-24e36e677fe9.jpg)

**Comment by Mcghee-Jake** [comment]
You should coordinate with Maco to see which plants you need images for. If they are real plants you should ideally have real pictures and if they are  fake plants you'll need fake  pictures. My oginal conception of the project was that we would do real posionius plants but if you both want to do fake ones I'm not super against it or anything. I would hold off on collecting image until you know which plants Maco is adding to the database

**Comment by mdoussias** [comment]
Yeah, for overall design... Do we want like a comedic site?  Or a more serious minded site.  
I'm down for either one.  Since I'm not doing the design as much, I'll leave this to Pavlos and Jake.

**Comment by mdoussias** [comment]
Clarificaiton:  I'll still help to make records and images etc.... I'll just search for whatever the you guys think is best.

**Comment by Mcghee-Jake** [comment]
Hey Maco,

I agree with you that resizing all the images so that they are the same size is a really good idea. One thing I have found useful is doing an advanced google image search and setting the proportions to 'square' so that it only returns square images. This is helpful so that when you resize the images to the same size none of them get stretched or squashed.

Also, I really want to add a slideshow/carousel to the main page of our store. This will most likely require us to have 2 image sizes (one for the slideshow, and one for the list results). So if you find images, can you make them all largish? Like 800x800, 700x700 or 600x600 would be good. Then I will resize them all individually to something smaller (like 200x200, needs experimenting) and rename the larger ones. The smaller images will just be [plantName.png] and i'll rename the larger ones [plantName-lg.png] so that we only have to store the path to the smaller ones in SQL and I can just find the path to the larger images with added code in the carousel.

Sorry that sounds like a mess. Basically what I am saying is that we could use images at this point and something like 800x800, 700x700 or 600x600 would be good. Just giving you some options in case you cant find square images of certain plants that are 800x800 or 700x700. 

I know that probably sounds confusing so let me know if you have any questions

**Comment by Mcghee-Jake** [comment]
Actually I'm since I'm pretty much done with my portion I can help get the images together. Though I think we still need more plants in the database to get images for.

**Comment by p12345vls** [comment]
I will collect some images tomorrow to add them in the database so that i can test them, until now I used url from online pictures. Hope tomorrow to complete everything. I deleted also the duplicated admin file from the file structure.

**Comment by p12345vls** [comment]
I connected store with admin and created header similar to store nav
https://pavlosp-p12345vls.c9users.io/cst336/CST336FinalProject/CST336/CST336FINAL/admin/login.php

**Comment by mdoussias** [comment]
All the images in the other repository have the same exact sizes.  If we can stick with that, that would be great.
https://github.com/team-makeSmart/CST336FINAL-PROJECT
