### ISSUE TITLE
FINAL PROPOSAL

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/CST336#13]
FINAL PROPOSAL 
NOTE Currently shared on Google docs.

We must submit a final proposal for approval.  Please discuss any issues here.

WE need to submit:

- [ ] preliminary diagram of the database  (To be complete by Maco)

- [ ] A write-up of what we plan to do (See shared google doc and edit as needed

Also, need to decide if the website will be:

- [ ] comedic plants

- [x] serious / realistic plants

**Comment by mdoussias** [comment]
If you check your email I started a google doc for the proposal.  But I made some assumptions. It can be easily changed.  I think most important, we jsut have to decide if the records will be funny or realistic.

**Comment by p12345vls** [comment]
Funny would be more interesting but realistic would be easier to find more records. I vote for realistic in order not to spent too much time searching for records.

**Comment by mdoussias** [comment]
I agree Pavlos, let's go with a realistic store.

**Comment by mdoussias** [comment]
I sent a draft of the ER DB diagram over slack.

**Comment by Mcghee-Jake** [comment]
Confirm realistic is going to be easier and will more professional imo
