### ISSUE TITLE
DB schema issue

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/CST336#15]
- [x]  Create views and SELECT statements for most general needs of the website

- [x] Ensure database SQL can be used in phpMyAdmin  (current files made in MySQL workbench)

- [x] Minor correction to schema priceDollar and priceCent and quantity should not be allowed to be null.  

- [x] admin.admin field in the admin table and customer.address field in the customer table both need to be unique fields.  Otherwise a user it will cause errors if two users have the same name when they try to log in.

**Comment by mdoussias** [comment]
I will try to correct these bugs the evening of July 25th, but I won't change any of the field or table names. 

Just be aware that it might cause issues if you accidentally create two admins with the same name.

**Comment by p12345vls** [comment]
I successfully created the database in phpmyadmin, I can set idadmin and username to unique until the  schema is updated

**Comment by mdoussias** [comment]
This task is done.  Some more records need created, but that is currently open on a separate issue.
[](https://github.com/team-makeSmart/CST336/issues/16)
