### ISSUE TITLE
DB Create Enough records for assignment

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/CST336#16]
- [ ]  Create enough database records to fulfill the assignment.

**Comment by Mcghee-Jake** [comment]
I think that the 'password' field in the customer table can be removed. Unless someone else wants to implement it, but personally I probably won't implement a customer login. The store was a lot of work already and right now I see it as a lot of work for not very much gain

**Comment by p12345vls** [comment]
If it not a requirement we do not need to implement it, we still have to get prepared for the final

**Comment by Mcghee-Jake** [comment]
Actually I think it makes more sense to open that up as a separate issue

**Comment by mdoussias** [comment]
This was completed, but unsure where to upload files.  File structure is getting done. 
In the meantime, if you need the most current SQL files see Slack for the file:
**sql files 08-05-18.zip**

Those files should work with heroku

**Comment by mdoussias** [comment]
This is done.  See the other repository.

**Comment by mdoussias** [comment]
This is done, see the other repository. 
https://github.com/team-makeSmart/CST336FINAL-PROJECT
