### ISSUE TITLE
Mockup

### ISSUE THREAD

**Issue by Mcghee-Jake** [team-makeSmart/CST336#2]

**Comment by mdoussias** [comment]
There is an initial mockup already started for the final proposal...It is in a Google doc already sent via email an still needs completed for the **final proposal** due 07-17-18.

**Comment by Mcghee-Jake** [comment]
Just a clarification, the proposal requirements don't say anything about the mockup. 

"
Each team member must submit the same Team Proposal.

Post here:

a) Project Description (main features of the app)
b) Potential database schema to use 
c) Division of labor
"

Unless I'm missing something

**Comment by Mcghee-Jake** [comment]
added mockups

**Comment by Mcghee-Jake** [comment]
I need to edit these so that they reflect all the changes we've made
