### ISSUE TITLE
ER Diagram

### ISSUE THREAD

**Issue by Mcghee-Jake** [team-makeSmart/CST336#3]

**Comment by mdoussias** [comment]
I'll try to make a very basic one by 07-15-18... 

I'm sure it will need edits, but then we can add or take away before we start coding.

**Comment by mdoussias** [comment]
This is mostly done.  Please make comments either here or on the google doc spreadsheet.  The link was sent over slack.  I made more tables than  we need.  We need to cut that down and I can finalize the design of the DB, or make any changes anyone wants.

**Comment by mdoussias** [comment]
FYI The least obvious two fields to me are the priceDollar and priceCent in the lineItem table.
The professor wanted these fields to keep track of the price at time of purchase.   That way you can change priceDollar and priceCent for new pricing in the plant table, without affecting the records of the old purchases.

**Comment by mdoussias** [comment]
The ER Diagram is completed.
