### ISSUE TITLE
imgLink

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/CST336#34]
In the **plant** table there is a field called **imgLink**, which will links to the image of a plant.
As I make the records, what format for the values should I put into this field  See below?
_'img/plant.png'_
_'plant.png'_

**Comment by p12345vls** [comment]
img/plant.png

**Comment by mdoussias** [comment]
Thank you Pavlos.

**Comment by mdoussias** [comment]
Leaving discussion open for Jake to read.  All records are being made with the format values of **img/plant.png**

**Comment by mdoussias** [comment]
This is done, see the other repository. 
https://github.com/team-makeSmart/CST336FINAL-PROJECT
