### ISSUE TITLE
Update file structure

### ISSUE THREAD

**Issue by p12345vls** [team-makeSmart/CST336#36]
File structure need to be updated should all files have root CST336FINAL
CST336FINAL
admin
docs
img
php
store
dbConnection

All href must be changed also. We have to do this because now the file structure is confusing.
![screen shot 2018-08-05 at 10 59 30 am](https://user-images.githubusercontent.com/32381448/43688508-032535f8-989f-11e8-8d5b-2aa5beaed75e.png)

![screen shot 2018-08-05 at 11 00 10 am](https://user-images.githubusercontent.com/32381448/43688510-09262732-989f-11e8-9556-264481d04a58.png)

**Comment by mdoussias** [comment]
Yeah, I thought this was fixed but somehow got lost.   

I'm not sure what are the current files

**Comment by mdoussias** [comment]
I'm really good with whatever you need.  But we need to settle the file structure now.... Otherwise we're going to be scrambling last minute to fix broken links.

**Comment by p12345vls** [comment]
I am fixing this right now, I dont know however if I would be able to push without conflicts after the file changing structure,

**Comment by p12345vls** [comment]
I will copy your new created files to the new structure before submit. We might need to create a new clean repository

**Comment by mdoussias** [comment]
Yeah, I don't understand what is going on.  The updates to the docs I made last night are missing. 

I have all the SQL statements ironed out.... I will send you the .zip file on slack

**Comment by p12345vls** [comment]
Ok

**Comment by mdoussias** [comment]
Let me know if you need help with the file structure.  I'll be back working about 2pm today until end of today.  I'm hoping to test and start fixing any bugs.

**Comment by p12345vls** [comment]
Ok

**Comment by mdoussias** [comment]
This is done, see the other repository. 
https://github.com/team-makeSmart/CST336FINAL-PROJECT
