### ISSUE TITLE
Database Design / Create Dummy Data

### ISSUE THREAD

**Issue by Mcghee-Jake** [team-makeSmart/CST336#5]
- Project must use at least four database tables
- The combined database tables must have at least ten fields
- One of the database table must have at least 20 records

**TO BE DONE IN STAGES:**

- [x] Maco to create a mockup database diagram and submit to Jake and Pavlos for approval:

- [x] Finalize database with any changes and add a few records for testing purposes

- [x] Populate with more records and create basic Query and Input statements 

- [x] Add "admin" table and update ER diagram.

- [ ] Finalize the database, create views, and ensure all records are in DB, enough to meet the requirements of the assignment

**Comment by Mcghee-Jake** [comment]
It might be a good to further divide this work (closing this issue and making multiple smaller ones)

**Comment by mdoussias** [comment]
I think I can handle this task.  Because the database names and format will affect the rest of the code, I'm thinking I will do in three parts:
- Create a Mockup / Database Diagram and submit to Jake and Pavlos for approval:
- Populate with a few records for testing purposes and clean up any issues 
- Populate with more records and create Query and input statements

**Comment by mdoussias** [comment]
I'll try to have the mockup done by end of day Sunday 07-15-18

**Comment by mdoussias** [comment]
One more note.  After I make the basic records needed to get the assignment completed, anyone of course can add more records, if they feel they have a couple funny plant names.

**Comment by Mcghee-Jake** [comment]
Reminder to self to add this one in later
 https://en.m.wikipedia.org/wiki/Heracleum_mantegazzianum

**Comment by mdoussias** [comment]
update to this string "admin" table is needed.  Will add 07-17-18

**Comment by mdoussias** [comment]
After feedback from professor, this will need more work.
I will try to add the additional functionality from the instructors feedback on the final proposal.
Hope to have done Friday 07-20-18, or early 07-21-18

**Comment by mdoussias** [comment]
This is done, mostly, but I found a few issues in creating the DB.  I will open a  separate issue and close this out.
