### ISSUE TITLE
Administrator Functionality

### ISSUE THREAD

**Issue by Mcghee-Jake** [team-makeSmart/CST336#9]
Requirements
- Administrators can login and logout from the system
- Administrators can update content of at least one table (using pre-populated data in the form)
- Administrators can insert new records in at least one table
- Administrators can delete records
- Administrators can generate at least three reports, which use aggregate functions (e.g., average price of all products in the table)

**Comment by Mcghee-Jake** [comment]
It might be a good to further divide this work (closing this issue and making multiple smaller ones)

**Comment by p12345vls** [comment]
This task is related to lab 6, I think it is not that complicated.

**Comment by Mcghee-Jake** [comment]
Good point, I didn't realize we were building this same functionality in lab 6. So yeah it definitely won't be as difficult as I initially thought.

**Comment by p12345vls** [comment]
I will take care of this

**Comment by p12345vls** [comment]
The admin will have access to a separate login page where they can login and then add delete and update records. we need to create a table 'admin' with first name, last name, username and password fields, sorry I forgot to mention it, I have actually completed lab 6

**Comment by mdoussias** [comment]
Ok.  I will do this tomorrow around 6pm.  This should be quick.

**Comment by p12345vls** [comment]
Correction: table admin. 
Fields: adminId, firstName, lastName, userName, password.

**Comment by mdoussias** [comment]
Cool.  Got it.  Will add tomorrow. 07-17-18

**Comment by p12345vls** [comment]
You can also check the document where it describes the requirements for the table, nothing complicated, but it should have a password set by SHA1 function. For example the password would be 'secret',  so it should be created as sha1('secret'). It is better to do it in the beginning than going back and make corrections.

https://docs.google.com/document/d/19F0nXxZ02vngB63IsPmr8bGxPDDaP03CQAFVRJLYOM0/edit#heading=h.h2a3q56yfny4

**Comment by mdoussias** [comment]
Will do.

**Comment by mdoussias** [comment]
Note that 'admin' in SQL is expected to become a keyword for some iterations of the SQL language.  However, I am sticking with the table 'admin' so as not to change what we already started and since it is not yet an SQL keyword.  Just an FYI....
   
https://docs.microsoft.com/en-us/sql/t-sql/language-elements/reserved-keywords-transact-sql?view=sql-server-2017

**Comment by p12345vls** [comment]
We forgot about this, I will do it

**Comment by p12345vls** [comment]
What I am using is named parameters, just the syntax is different.    insert(...) values(???);

**Comment by p12345vls** [comment]
Or maybe they are positional parameters..

**Comment by Mcghee-Jake** [comment]
Hmmm I'm not sure but I wouldn't be surprised if the professor docks points for not using named parameters. It's not too difficult to implement.

**Comment by p12345vls** [comment]
I remember I had some trouble with that, but I ll try again, no problem

**Comment by Mcghee-Jake** [comment]
Make sure to take a look at the ottermart_admin addproduct and updateproduct pages. They are very similar to what your page is like and they have a perfect example of how to implement the named parameters.

**Comment by p12345vls** [comment]
Done with named parameters. 
Need also
1.  check for invalid user input
2. add a header with a button to link to the store page
3. header with color and font similar with the store page

Will do all these on Saturday after the final.
